package co.byite.focus.core.aggregate

import co.byite.focus.core.Synth
import co.byite.focus.core.log.SessionLog
import co.byite.focus.core.model.AppState
import co.byite.focus.core.model.FaceSchedule
import co.byite.focus.core.model.ScreenState
import co.byite.focus.core.model.SessionEnd
import co.byite.focus.core.model.SessionEndReason
import co.byite.focus.core.model.SessionHeader
import co.byite.focus.core.report.ComparisonState
import co.byite.focus.core.report.StopSummary
import co.byite.focus.core.report.V0bReport
import co.byite.focus.core.util.Stats
import kotlin.math.abs
import kotlin.math.roundToLong
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Directive E 9장 (a)~(o): the selected timestamp lists are generated by the production [FrameScheduler] and counted by
 * the production [FeatureAggregator], [StopSequence] and [V0bReport]. The harness below is the analysis-thread glue
 * of `CameraPipeline.analyze` reduced to its counter calls: capture result → scheduler, analyzer frame → scheduler →
 * (skip | Face outcome), in the order the events reach the analysis thread. Every time is raw camera ns; the mono
 * conversion is a per-path offset so UNKNOWN-source devices (two conversion paths, different offsets) can be modelled.
 */
private val device = DeviceSample(thermalStatus = 0, isInteractive = false, isDeviceIdle = false, screenState = ScreenState.OFF, appState = AppState.BACKGROUND)

class SlotSchedulingTest {

    private fun ms(x: Double): Long = (x * 1_000_000.0).roundToLong()

    /** Nominal camera frame interval and Face period in ns. */
    private val frame24 = GapThresholds.frameIntervalNs(24)
    private val period15 = GapThresholds.periodNs(15.0)
    private val period12 = GapThresholds.periodNs(12.0)

    /**
     * Session harness: raw camera timestamps, two offsets (capture results are converted with [crOffsetNs], analyzer
     * frames with [frameOffsetNs] — 0/0 models a REALTIME camera), the production scheduler and aggregator.
     */
    private class Session(
        val startRaw: Long,
        processPeriodNs: Long?,
        frameIntervalNs: Long,
        val crOffsetNs: Long = 0L,
        val frameOffsetNs: Long = 0L,
        sink: (FeatureAggregator) -> CameraCounterSink = { it },
        gapNs: Long = GapThresholds.gapThresholdNs(processPeriodNs ?: frameIntervalNs),
        longGapNs: Long = GapThresholds.longGapThresholdNs(processPeriodNs ?: frameIntervalNs),
        /** fps unset (E2 1장): no expected interval at the start; the aggregator learns the diagnostic one from the warm-up. */
        learnFromWarmup: Boolean = false,
    ) {
        val startMonoMs: Long = (startRaw + frameOffsetNs) / 1_000_000L
        val agg = FeatureAggregator(
            startMonoMs, Synth.UTC0, gapThresholdNs = gapNs, longGapThresholdNs = longGapNs, sessionStartRawNs = startRaw,
            expectedIntervalNs = processPeriodNs ?: frameIntervalNs, learnThresholdsFromWarmup = learnFromWarmup,
        )
        val scheduler = FrameScheduler(sink(agg), processPeriodNs, frameIntervalNs)
        val filledRaw = ArrayList<Long>()
        var started = false

        fun cr(raw: Long) = CameraStamp(raw, raw + crOffsetNs)
        fun fr(raw: Long) = CameraStamp(raw, raw + frameOffsetNs)

        fun captureResult(raw: Long): FrameScheduler.CaptureDecision = scheduler.onCaptureResult(cr(raw))

        /** An analyzer frame; [face] = Face succeeds, else a Face inference error. Returns the scheduler's outcome. */
        fun frame(raw: Long, face: Boolean = true, faceInferMs: Double = 15.0): FrameScheduler.FrameOutcome {
            val st = fr(raw)
            if (!started) {
                started = true
                agg.onScene(SceneSample(st.captureMonoNs, 118.0, 4.0, 9.0, rawSensorTs = raw))
                scheduler.onSessionStart(st)
            }
            val out = scheduler.onFrameReceived(st)
            when (out) {
                FrameScheduler.FrameOutcome.SLOT -> {
                    if (face) {
                        scheduler.onFaceSucceeded(st)
                        filledRaw.add(raw)
                        agg.onFrameProcessed(ProcessedFrame(st.captureMonoNs, faceInferMs, FrameSample(st.captureMonoNs, 1_000_000L, false, rawSensorTs = raw), rawSensorTs = raw))
                    } else {
                        scheduler.onFaceInferenceError(st)
                    }
                }
                FrameScheduler.FrameOutcome.NOT_SLOT -> scheduler.onFrameSkipped(st)
                FrameScheduler.FrameOutcome.OUT_OF_ORDER -> scheduler.onPreFaceError(st)
                FrameScheduler.FrameOutcome.AFTER_FENCE -> Unit
            }
            return out
        }

        /** The normal path of one captured frame: capture result then its analyzer frame. */
        fun both(raw: Long, face: Boolean = true) {
            captureResult(raw)
            frame(raw, face)
        }

        fun closeAll(nowMonoMs: Long) = agg.closeBuckets(nowMonoMs, device)

        /** The normal stop order with a clean drain, as [StopSequence] runs it. */
        fun stop(fenceRaw: Long, captureResultsDrained: Boolean = true, queueDrained: Boolean = true): StopResult = StopSequence(
            stopInputs = { fenceRaw / 1_000_000L },
            raiseFence = { f -> scheduler.fence(fenceRaw); agg.stopInputs(f, fenceRaw) },
            drainCaptureResults = { captureResultsDrained },
            awaitAnalysisIdle = { 0L },
            closeSlotScheduler = { scheduler.close() },
            closePoseSlot = { },
            awaitPoseIdle = { 0L },
            drainAggregationQueue = { queueDrained },
            finish = { f -> StopFinalizer.finish(agg, f, startMonoMs, Synth.UTC0, device, SessionEndReason.USER) },
            writeEnd = { },
        ).run()
    }

    /** A 0.2.4 header with a fixed [24,24] request, so the summary's first line is about the condition under test only. */
    private fun fixedHeader(preset: String, schedule: FaceSchedule, periodNs: Long, startMonoMs: Long): SessionHeader = Synth.header.copy(
        tStartMonoMs = startMonoMs, capturePreset = preset, cameraFpsRequestLower = 24, cameraFpsRequestUpper = 24, cameraFpsRangesSupported = "[24,24],[30,30]", nominalFps = 24,
        faceSchedule = schedule, faceProcessPeriodNs = periodNs, frameGapThresholdNs = GapThresholds.gapThresholdNs(periodNs), frameLongGapThresholdNs = GapThresholds.longGapThresholdNs(periodNs),
    )

    private val checkedStop = StopSummary(checked = true, captureResultDrainComplete = true, aggregationQueueDrained = true)

    private fun stream(fps: Double, seconds: Double, startRaw: Long = 5_000_000_000L): List<Long> {
        val n = (fps * seconds).toInt()
        val interval = 1e9 / fps
        return (0 until n).map { startRaw + (it * interval).roundToLong() }
    }

    // ---- (a) 24.000 fps → 15 Hz, long run: filled ≈ 15 Hz, intervals are 41.7 / 83.3 only

    @Test
    fun a_twentyFourFpsToFifteenHzFillsAtFifteenHzWithOnlyOneAndTwoFrameIntervals() {
        val raws = stream(24.0, 600.0) // 10 minutes, 14 400 frames
        val s = Session(raws[0], period15, frame24)
        for (r in raws) s.both(r)
        val filled = s.filledRaw
        val spanS = (filled.last() - filled.first()) / 1e9
        val rate = (filled.size - 1) / spanS
        assertTrue(abs(rate - 15.0) < 0.02, "filled rate $rate Hz")
        val intervals = filled.zipWithNext { a, b -> b - a }.map { (it / 1e5).roundToLong() / 10.0 }.toSet() // 0.1 ms resolution
        assertEquals(setOf(41.7, 83.3), intervals, "only one-frame and two-frame intervals occur")
        assertEquals(0L, s.scheduler.slotsMissed)
        assertEquals(s.scheduler.slotsExpected, s.scheduler.slotsFilled)
        assertEquals(listOf(0.0, 83.3, 125.0, 208.3, 250.0, 333.3), filled.take(6).map { ((it - raws[0]) / 1e5).roundToLong() / 10.0 }, "directive E 3장 example phase")
        val t = s.agg.totals
        assertEquals(t.processingSlotsExpected, t.processingSlotsFilled + t.processingSlotsMissed)
        assertEquals(raws.size.toLong(), t.framesRequested)
        assertEquals(t.framesRequested - t.framesProcessed, t.framesSkippedIntentional)
        assertEquals(emptyList(), CounterConsistency.check(t))
    }

    // ---- (b) 23.98 fps → 15 Hz, 8 minutes, no loss: missed = 0

    @Test
    fun b_realCadenceTwentyThreePointNinetyEightToFifteenHzForEightMinutesMissesNothing() {
        val raws = stream(23.98, 480.0)
        val s = Session(raws[0], period15, frame24)
        for (r in raws) s.both(r)
        assertEquals(0L, s.scheduler.slotsMissed)
        assertEquals(0L, s.agg.totals.processingSlotsMissed)
        assertEquals(s.agg.totals.processingSlotsExpected, s.agg.totals.processingSlotsFilled)
        val rate = (s.filledRaw.size - 1) / ((s.filledRaw.last() - s.filledRaw.first()) / 1e9)
        assertTrue(abs(rate - 15.0) < 0.02, "filled rate $rate Hz")
        // the phase never accumulates: every selected frame lies within half a (real) frame interval of a slot target
        val anchor = s.scheduler.anchorRawTs!!
        val halfReal = (1e9 / 23.98 / 2).roundToLong() + 100_000L
        for (f in s.filledRaw) {
            val phase = (f - anchor) % period15
            val dist = minOf(phase, period15 - phase)
            assertTrue(dist <= halfReal, "frame $f is ${dist / 1e6} ms from a slot target")
        }
        assertEquals(emptyList(), CounterConsistency.check(s.agg.totals))
    }

    // ---- (c) 24 fps → 12 Hz: filled ≈ 12 Hz

    @Test
    fun c_twentyFourFpsToTwelveHzFillsEveryOtherFrame() {
        val raws = stream(24.0, 120.0)
        val s = Session(raws[0], period12, frame24)
        for (r in raws) s.both(r)
        val rate = (s.filledRaw.size - 1) / ((s.filledRaw.last() - s.filledRaw.first()) / 1e9)
        assertTrue(abs(rate - 12.0) < 0.02, "filled rate $rate Hz")
        assertEquals(setOf(83_333_333L, 83_333_334L).intersect(s.filledRaw.zipWithNext { a, b -> b - a }.toSet()).isNotEmpty(), true)
        assertTrue(s.filledRaw.zipWithNext { a, b -> b - a }.all { abs(it - 83_333_333L) <= 1L }, "every other frame")
        assertEquals(raws.size / 2L, s.agg.totals.framesSkippedIntentional)
        assertEquals(0L, s.scheduler.slotsMissed)
    }

    // ---- (d) a 500 ms capture gap: catch-up keeps the phase

    @Test
    fun d_afterACaptureGapTheCatchUpKeepsTheTargetPhase() {
        val start = 5_000_000_000L
        val s = Session(start, period15, frame24)
        val before = (0 until 48).map { start + (it * frame24) } // 2 s at 24 fps
        for (r in before) s.both(r)
        val lastBefore = s.filledRaw.last()
        val gapNs = 500_000_000L
        val resume = before.last() + frame24 + gapNs
        val after = (0 until 480).map { resume + it * frame24 } // 20 s: the 41.7 / 83.3 alternation averages out
        for (r in after) s.both(r)
        val anchor = s.scheduler.anchorRawTs!!
        assertEquals(start, anchor)
        assertEquals(0L, (s.scheduler.nextDueRawTs - anchor) % period15, "next_due stays on the anchor phase after the catch-up")
        val filledAfter = s.filledRaw.filter { it > lastBefore }
        assertTrue(filledAfter.size > 2)
        assertEquals(resume, filledAfter.first(), "the first frame after the gap fills the slot that was due during the gap")
        for (f in filledAfter.drop(1)) {
            val phase = (f - anchor) % period15
            val dist = minOf(phase, period15 - phase)
            assertTrue(dist <= frame24 / 2 + 1, "frame $f after the gap is ${dist / 1e6} ms from a slot target: the phase slipped")
        }
        val steady = filledAfter.drop(1)
        val afterRate = (steady.size - 1) / ((steady.last() - steady.first()) / 1e9)
        assertTrue(abs(afterRate - 15.0) < 0.05, "rate after the gap $afterRate Hz")
        // re-anchoring to the resumed frame (the rejected design, 정정 3) would have put every later slot 33 ms off this phase
        assertTrue(((resume - anchor) % period15).let { minOf(it, period15 - it) } > frame24 / 2, "the resumed frame itself is off-phase, so the check above is meaningful")
        assertEquals(0L, s.scheduler.slotsMissed, "a capture gap is a gap, not a missed slot: no frame was selected during it")
        // the gap itself is visible as a long gap in the aggregator (period 66.7 ms → long threshold 300 ms)
        val closed = s.closeAll(s.startMonoMs + 30_000)
        assertEquals(1, closed.sumOf { it.second.gapsOverLongThreshold })
    }

    // ---- (e) UNKNOWN camera clock: the two conversion paths differ by a few ms, filled still matches by raw identity

    @Test
    fun e_differentOffsetsOnTheTwoConversionPathsDoNotBreakSlotIdentity() {
        val raws = stream(24.0, 30.0)
        // capture results converted with the provisional offset (2 ms), analyzer frames with the settled one (6 ms)
        val s = Session(raws[0], period15, frame24, crOffsetNs = 2_000_000L, frameOffsetNs = 6_000_000L)
        for (r in raws) s.both(r)
        val t = s.agg.totals
        assertEquals(0L, t.processingSlotsMissed)
        assertEquals(t.processingSlotsExpected, t.processingSlotsFilled)
        assertEquals(raws.size.toLong(), t.framesRequested)
        assertEquals(0L, t.captureResultsBeforeStart, "the first frame's capture result has raw == start: inside the window although its mono value precedes the mono start")
        assertEquals(0L, t.inputsBeforeStart)
        assertEquals(emptyList(), CounterConsistency.check(t))
        // every-frame preset on the same clocks: slot per capture result, all filled
        val e = Session(raws[0], null, frame24, crOffsetNs = 2_000_000L, frameOffsetNs = 6_000_000L)
        for (r in raws) e.both(r)
        assertEquals(raws.size.toLong(), e.agg.totals.processingSlotsExpected)
        assertEquals(raws.size.toLong(), e.agg.totals.processingSlotsFilled)
    }

    // ---- (f) capture results before the session start are not expected; the first frame's own capture result is the first slot

    @Test
    fun f_captureResultsBeforeTheStartAreReplayedButNeverExpectedAndTheFirstFrameIsTheFirstSlot() {
        val start = 5_000_000_000L
        val s = Session(start, period15, frame24)
        val early = listOf(start - 3 * frame24, start - 2 * frame24, start - frame24)
        for (r in early) assertEquals(FrameScheduler.CaptureDecision.PENDING, s.captureResult(r))
        assertEquals(FrameScheduler.CaptureDecision.PENDING, s.captureResult(start), "the first frame's capture result arrives before its image")
        assertEquals(FrameScheduler.CaptureDecision.PENDING, s.captureResult(start + frame24))
        assertEquals(FrameScheduler.FrameOutcome.SLOT, s.frame(start), "replay: the capture result of the first frame is the first processing opportunity")
        assertEquals(start, s.scheduler.anchorRawTs)
        assertEquals(3L, s.scheduler.replayedBeforeStart)
        val t = s.agg.totals
        assertEquals(3L, t.captureResultsBeforeStart)
        assertEquals(3L, t.inputsBeforeStart)
        assertEquals(2L, t.framesRequested, "start and start+1 are inside the window")
        assertEquals(1L, t.processingSlotsExpected, "the 3 early results opened no slot; start did; start+1 is 41.7 ms after the 66.7 ms target")
        assertEquals(1L, t.processingSlotsFilled)
        assertEquals(listOf(start), s.filledRaw)
        // its capture result arriving *after* the image is a duplicate, still counted as requested, not as a new slot
        val s2 = Session(start, period15, frame24)
        for (r in early) s2.captureResult(r)
        assertEquals(FrameScheduler.FrameOutcome.SLOT, s2.frame(start))
        assertEquals(FrameScheduler.CaptureDecision.DUPLICATE, s2.captureResult(start))
        assertEquals(1L, s2.agg.totals.framesRequested)
        assertEquals(1L, s2.agg.totals.processingSlotsExpected)
    }

    // ---- (g) two processing opportunities captured before the fence never reach the analyzer: expected +2, missed +2

    @Test
    fun g_slotsLostToBackpressureBeforeTheFenceAreExpectedAndMissed() {
        val raws = stream(24.0, 2.0)
        val s = Session(raws[0], period15, frame24)
        for (r in raws) s.both(r)
        val e0 = s.agg.totals.processingSlotsExpected
        // later frames are captured (capture results arrive) but KEEP_ONLY_LATEST drops their images: feed until two slots opened
        var raw = raws.last()
        var fed = 0
        var selected = 0
        while (selected < 2) {
            raw += frame24
            fed++
            if (s.captureResult(raw) == FrameScheduler.CaptureDecision.SELECTED) selected++
        }
        assertTrue(fed in 2..4, "two slots need 2–4 frames at 15 Hz on 24 fps, fed $fed")
        val fenceRaw = raw + frame24 / 2
        s.scheduler.fence(fenceRaw)
        s.agg.stopInputs((fenceRaw) / 1_000_000L, fenceRaw)
        assertEquals(2L, s.scheduler.close(), "CLOSE terminates both open slots as missed")
        val t = s.agg.totals
        assertEquals(e0 + 2, t.processingSlotsExpected)
        assertEquals(2L, t.processingSlotsMissed)
        assertEquals(e0, t.processingSlotsFilled)
        assertEquals(fed.toLong(), t.backpressureDrops, "every capture result without an analyzer frame")
        assertEquals(emptyList(), CounterConsistency.check(t))
        // the same loss noticed by a later frame instead of CLOSE: missed by backpressure
        val s3 = Session(raws[0], period15, frame24)
        for (r in raws) s3.both(r)
        var lost = raws.last()
        do { lost += frame24 } while (s3.captureResult(lost) != FrameScheduler.CaptureDecision.SELECTED)
        s3.frame(lost + 2 * frame24)
        assertEquals(1L, s3.scheduler.slotsMissedByBackpressure)
        assertEquals(1L, s3.agg.totals.processingSlotsMissed)
    }

    // ---- (h) three capture results captured after the fence arrive before CLOSE: expected unchanged, after_fence = 3, analyzer rejects the same three

    @Test
    fun h_captureResultsAndFramesAfterTheRawFenceAreRejectedAndCountedNotExpected() {
        val raws = stream(24.0, 2.0)
        val s = Session(raws[0], period15, frame24)
        for (r in raws) s.both(r)
        val e0 = s.agg.totals.processingSlotsExpected
        val fenceRaw = raws.last() + frame24 / 2
        s.scheduler.fence(fenceRaw)
        s.agg.stopInputs(fenceRaw / 1_000_000L, fenceRaw)
        val late = (1..3).map { raws.last() + it * frame24 }
        for (r in late) assertEquals(FrameScheduler.CaptureDecision.AFTER_FENCE, s.captureResult(r))
        for (r in late) assertEquals(FrameScheduler.FrameOutcome.AFTER_FENCE, s.frame(r))
        val t = s.agg.totals
        assertEquals(e0, t.processingSlotsExpected)
        assertEquals(3L, t.captureResultsAfterFence)
        assertEquals(6L, t.inputsAfterFence, "3 capture results + 3 analyzer frames were rejected")
        assertEquals(3L, s.scheduler.framesRejectedAfterFence)
        assertEquals(raws.size.toLong(), t.framesRequested)
        assertEquals(raws.size.toLong(), t.framesAnalyzerReceived)
        assertEquals(0L, s.scheduler.close())
        assertEquals(0L, t.captureResultsAfterClose)
        assertEquals(emptyList(), CounterConsistency.check(s.agg.totals))
    }

    // ---- (i) UNKNOWN: the frame just before the fence was converted with the old offset (mono > fenceMono), Face finishes after the fence

    @Test
    fun i_aPreFenceFrameWhoseMonoValuePassedTheMonoFenceIsStillProcessedAndAppliedByRawIdentity() {
        val raws = stream(24.0, 3.0)
        val oldOffset = 8_000_000L
        val s = Session(raws[0], null, frame24, crOffsetNs = oldOffset, frameOffsetNs = oldOffset)
        for (r in raws.dropLast(1)) s.both(r)
        val lastRaw = raws.last()
        // the frozen offset at the fence is smaller (the estimator settled): fenceRaw = fenceMono − offsetSnapshot
        val snapshot = 2_000_000L
        val fenceMonoNs = lastRaw + snapshot + 1_000_000L // 1 ms after the last frame on the frozen clock
        val fenceRaw = fenceMonoNs - snapshot
        assertTrue(lastRaw < fenceRaw)
        val frameMono = lastRaw + oldOffset // converted before the freeze: past the mono fence
        assertTrue(frameMono > fenceMonoNs)
        s.captureResult(lastRaw) // capture result of the last frame, in the window by raw
        s.scheduler.fence(fenceRaw)
        s.agg.stopInputs(fenceMonoNs / 1_000_000L, fenceRaw)
        // Face on the in-flight frame completes after the fence
        val st = CameraStamp(lastRaw, frameMono)
        assertEquals(FrameScheduler.FrameOutcome.SLOT, s.scheduler.onFrameReceived(st))
        assertTrue(s.scheduler.onFaceSucceeded(st))
        s.agg.onFrameProcessed(ProcessedFrame(frameMono, 15.0, FrameSample(frameMono, 1_000_000L, false, rawSensorTs = lastRaw), rawSensorTs = lastRaw))
        assertEquals(0L, s.scheduler.close())
        val t = s.agg.totals
        assertEquals(raws.size.toLong(), t.framesRequested)
        assertEquals(raws.size.toLong(), t.framesAnalyzerReceived)
        assertEquals(raws.size.toLong(), t.framesProcessed)
        assertEquals(raws.size.toLong(), t.framesSampleApplied)
        assertEquals(0L, t.framesSampleLateDropped)
        assertEquals(0L, t.inputsAfterFence)
        assertEquals(0L, t.captureResultsAfterFence)
        assertEquals(0L, t.processingSlotsMissed)
        assertEquals(raws.size.toLong(), t.processingSlotsFilled)
        assertEquals(emptyList(), CounterConsistency.check(t))
        val out = StopFinalizer.finish(s.agg, fenceMonoNs / 1_000_000L, s.startMonoMs, Synth.UTC0, device, SessionEndReason.USER)
        assertEquals(t, out.totals.copy(), "finish changes no total")
        assertEquals(false, out.end.stopIntegrityFailed)
    }

    // ---- (j) start clamp and end clamp

    @Test
    fun j_theFirstFramesCaptureResultWithAnOlderMonoValueLandsInBucketZeroAndTheEndSideInTheLastPartialBucket() {
        val start = 5_000_000_000L
        // the first frame's capture result was converted before anything was estimated (offset 0); from the first analyzer
        // frame on the estimator's provisional offset (30 ms) applies to both paths
        val s = Session(start, null, frame24, crOffsetNs = 30_000_000L, frameOffsetNs = 30_000_000L)
        val raws = (0 until 48).map { start + it * frame24 }
        assertEquals(FrameScheduler.CaptureDecision.PENDING, s.scheduler.onCaptureResult(CameraStamp(start, start)))
        s.frame(start)
        assertTrue(start < s.startMonoMs * 1_000_000L, "old-offset mono value precedes the mono session start")
        for (r in raws.drop(1)) s.both(r)
        val closed = s.closeAll(s.startMonoMs + 1_300)
        assertEquals(1, closed.size)
        val b0 = closed[0].second
        assertEquals(b0.framesRequested, b0.framesAnalyzerReceived, "the first second conserves requested = backpressure + received")
        assertEquals(0, b0.backpressureDrops)
        assertEquals(24, b0.framesRequested)
        assertEquals(0L, s.agg.totals.captureResultsBeforeStart)
        // end side (symmetric): a frame captured inside the raw window whose mono value — converted with a stale, larger
        // offset — lies more than a bucket past the mono fence. It goes through the scheduler like a real frame.
        val fenceRaw = raws.last() + 3 * frame24 // ≈ 2083 ms raw, 2113 ms mono: bucket 1 (ends at 2030 ms mono) is complete
        val fenceMonoMs = (fenceRaw + 30_000_000L) / 1_000_000L
        s.scheduler.fence(fenceRaw)
        s.agg.stopInputs(fenceMonoMs, fenceRaw)
        val straggler = raws.last() + frame24 // raw < fenceRaw
        val staleMono = fenceMonoMs * 1_000_000L + 1_500_000_000L // 1.5 s past the mono fence: two buckets beyond the last partial one
        val before = s.agg.totals
        val st = CameraStamp(straggler, staleMono)
        assertEquals(FrameScheduler.CaptureDecision.SELECTED, s.scheduler.onCaptureResult(st))
        assertEquals(FrameScheduler.FrameOutcome.SLOT, s.scheduler.onFrameReceived(st))
        assertTrue(s.scheduler.onFaceSucceeded(st))
        s.agg.onFrameProcessed(ProcessedFrame(staleMono, 15.0, FrameSample(staleMono, 1_000_000L, false, rawSensorTs = straggler), rawSensorTs = straggler))
        val t = s.agg.totals
        assertEquals(before.framesRequested + 1, t.framesRequested, "raw < fenceRaw: admitted whatever the mono value")
        assertEquals(before.framesAnalyzerReceived + 1, t.framesAnalyzerReceived)
        assertEquals(before.framesProcessed + 1, t.framesProcessed)
        assertEquals(before.framesSampleApplied + 1, t.framesSampleApplied, "clamped to the last partial bucket and applied, not late")
        assertEquals(0L, t.framesSampleLateDropped)
        assertEquals(before.processingSlotsFilled + 1, t.processingSlotsFilled)
        assertEquals(0L, t.inputsAfterFence)
        assertEquals(0L, t.captureResultsAfterFence)
        val out = StopFinalizer.finish(s.agg, fenceMonoMs, s.startMonoMs, Synth.UTC0, device, SessionEndReason.USER, closed)
        assertEquals(2, out.records.size, "buckets 0 and 1 are complete; the partial one is dropped but its counts stay in the totals")
        assertEquals(before.framesRequested + 1, out.totals.framesRequested)
        assertEquals(emptyList(), CounterConsistency.check(out.totals))
        // the same stamp without the clamp would have opened bucket 3, two past the fence: finish must still emit nothing after the fence
        assertTrue(out.records.all { it.second.tMonoMs + 1000 <= fenceMonoMs })
    }

    // ---- (k) a normal stop: expected = filled + missed is part of the stop check, after_close = 0

    @Test
    fun k_theNormalStopChecksTheSlotRelationAndHasNoCaptureResultAfterClose() {
        val raws = stream(24.0, 2.5)
        val s = Session(raws[0], period15, frame24)
        for (r in raws) s.both(r)
        val fenceRaw = raws.last() + frame24 / 2
        val fenceMs = fenceRaw / 1_000_000L
        val r = StopSequence(
            stopInputs = { fenceMs },
            raiseFence = { f -> s.scheduler.fence(fenceRaw); s.agg.stopInputs(f, fenceRaw) },
            awaitAnalysisIdle = { 0L },
            closeSlotScheduler = { s.scheduler.close() },
            closePoseSlot = { },
            awaitPoseIdle = { 0L },
            drainAggregationQueue = { true },
            finish = { f -> StopFinalizer.finish(s.agg, f, s.startMonoMs, Synth.UTC0, device, SessionEndReason.USER) },
            writeEnd = { },
        ).run()
        assertEquals(StopSequence.ORDER, r.steps)
        assertTrue(StopSequence.STEP_CLOSE_SLOTS in r.steps)
        assertEquals(0L, r.slotsClosedAsMissed)
        assertEquals(emptyList(), r.mismatches)
        assertEquals(r.totals.processingSlotsExpected, r.totals.processingSlotsFilled + r.totals.processingSlotsMissed)
        assertTrue(r.totals.processingSlotsExpected > 0)
        assertEquals(0L, r.totals.captureResultsAfterClose)
        assertFalse(r.stopIntegrityFailed)
        assertEquals(false, r.end.stopIntegrityFailed)
        assertEquals(0L, r.end.captureResultsAfterClose)
        assertEquals(fenceMs, r.end.tMonoMs)
    }

    // ---- (l) cadence mismatch on a fixed request; never on a variable one

    private fun cadenceLog(requested: Int, lower: Int?, upper: Int?, preset: String = "A"): SessionLog {
        val records = (0L until 100L).map { Synth.record(it).copy(framesRequested = requested, framesAnalyzerReceived = requested, framesProcessed = requested, framesSampleApplied = requested) }
        val h = Synth.header.copy(
            capturePreset = preset, cameraFpsRequestLower = lower, cameraFpsRequestUpper = upper, nominalFps = upper ?: 24,
            faceSchedule = FaceSchedule.EVERY_FRAME, faceProcessPeriodNs = frame24, frameGapThresholdNs = GapThresholds.gapThresholdNs(frame24), frameLongGapThresholdNs = GapThresholds.longGapThresholdNs(frame24),
        )
        return SessionLog(h, records, sessionEnd = co.byite.focus.core.model.SessionEnd(Synth.mono(100), Synth.utc(100), SessionEndReason.USER))
    }

    @Test
    fun l_aFixedRequestWhoseMeasuredCadenceIsOffByMoreThanThreePercentIsFlaggedButNotAVariableOne() {
        // 23.2 fps measured against [24,24]: 100 seconds with 23 or 24 capture results
        val records = (0L until 100L).map { sec -> val n = if (sec % 5 == 0L) 24 else 23; Synth.record(sec).copy(framesRequested = n, framesAnalyzerReceived = n, framesProcessed = n, framesSampleApplied = n) }
        val fixed = cadenceLog(24, 24, 24).let { it.copy(records = records) }
        val s = V0bReport.build(fixed, stop = checkedStop)
        assertEquals(23.2, s.overall.cadence.measuredFps!!, 1e-9)
        assertEquals(true, s.overall.cadence.mismatch)
        assertEquals(ComparisonState.NOT_COMPARABLE, s.comparability.state)
        assertEquals(listOf("${V0bReport.REASON_CADENCE}(요청 [24,24], 실측 23.20fps)"), s.comparability.reasons)
        val text = s.render()
        assertEquals(V0bReport.NOT_COMPARABLE_PREFIX + "${V0bReport.REASON_CADENCE}(요청 [24,24], 실측 23.20fps)", text.lines()[0], text)
        assertEquals(V0bReport.COUNTER_OK, text.lines()[1], text)
        assertTrue(text.lines()[2].startsWith(V0bReport.CADENCE_MISMATCH_PREFIX), text)
        // Hvar: the same records under a variable range [7,15] are never a mismatch, nothing is judged, and the first line is the third state (not "비교 불가")
        val hvar = V0bReport.build(cadenceLog(15, 7, 15, preset = "Hvar").let { it.copy(records = records.map { r -> r.copy(framesRequested = 14, framesAnalyzerReceived = 14, framesProcessed = 14, framesSampleApplied = 14) }) }, stop = checkedStop)
        assertNull(hvar.overall.cadence.mismatch)
        assertEquals(false, hvar.overall.cadence.requestFixed)
        assertFalse(hvar.overall.thresholds.applicable)
        assertEquals("n/a", hvar.overall.thresholds.gapLabel)
        assertFalse(hvar.pass.judged)
        assertNull(hvar.pass.pass)
        assertEquals(ComparisonState.NOT_APPLICABLE, hvar.comparability.state)
        val ht = hvar.render()
        assertEquals(V0bReport.NOT_APPLICABLE_LINE, ht.lines()[0], ht)
        assertFalse(ht.lines().any { it.startsWith(V0bReport.CADENCE_MISMATCH_PREFIX) }, ht)
        assertTrue("합격 판정 안 함(프리셋 Hvar, 가변 cadence [7,15])" in ht, ht)
        assertTrue("갭 임계: n/a / 긴 갭 n/a" in ht, ht)
        // a fixed request within 3 % is not flagged: the session is comparable
        val ok = V0bReport.build(cadenceLog(24, 24, 24), stop = checkedStop)
        assertEquals(false, ok.overall.cadence.mismatch)
        assertEquals(ComparisonState.COMPARABLE, ok.comparability.state)
        assertEquals(V0bReport.COMPARABLE_LINE, ok.render().lines()[0])
        assertFalse(ok.render().lines().any { it.startsWith(V0bReport.CADENCE_MISMATCH_PREFIX) })
    }

    // ---- (m) a slot lost between the scheduler and the counters breaks expected = filled + missed at the stop check

    @Test
    fun m_aSlotThatIsNeitherFilledNorMissedFailsTheStopCheck() {
        val raws = stream(24.0, 2.0)
        var dropOne = true
        val s = Session(raws[0], period15, frame24, sink = { agg ->
            object : CameraCounterSink by agg {
                override fun onSlotFilled(stamp: CameraStamp) {
                    if (dropOne) { dropOne = false; return } // injected bug: one filled event never reaches the counters
                    agg.onSlotFilled(stamp)
                }
            }
        })
        for (r in raws) s.both(r)
        val fenceRaw = raws.last() + frame24 / 2
        val r = StopSequence(
            stopInputs = { fenceRaw / 1_000_000L },
            raiseFence = { f -> s.scheduler.fence(fenceRaw); s.agg.stopInputs(f, fenceRaw) },
            awaitAnalysisIdle = { 0L },
            closeSlotScheduler = { s.scheduler.close() },
            closePoseSlot = { },
            awaitPoseIdle = { 0L },
            drainAggregationQueue = { true },
            finish = { f -> StopFinalizer.finish(s.agg, f, s.startMonoMs, Synth.UTC0, device, SessionEndReason.USER) },
            writeEnd = { },
        ).run()
        assertEquals(1, r.mismatches.size, r.mismatches.toString())
        assertTrue(r.mismatches[0].startsWith("processing_slots_expected"), r.mismatches[0])
        assertEquals(r.totals.processingSlotsExpected - 1, r.totals.processingSlotsFilled + r.totals.processingSlotsMissed)
    }

    // ---- (n) gap-threshold formula at 24 / 15 / 12

    @Test
    fun n_gapThresholdsAreTheFormulaAndClassifyByFrameCountAtEveryCadence() {
        assertEquals(41_666_667L, frame24)
        assertEquals(62_500_000L, GapThresholds.gapThresholdNs(frame24))
        assertTrue(abs(GapThresholds.longGapThresholdNs(frame24) - 187_500_000L) <= 2L, "187.5 ms within the ns rounding of the period")
        assertTrue(abs(GapThresholds.gapThresholdNs(period15) - 100_000_000L) <= 2L)
        assertTrue(abs(GapThresholds.longGapThresholdNs(period15) - 300_000_000L) <= 2L)
        assertTrue(abs(GapThresholds.gapThresholdNs(period12) - 125_000_000L) <= 2L)
        assertTrue(abs(GapThresholds.longGapThresholdNs(period12) - 375_000_000L) <= 2L)
        for ((fps, period) in listOf(24 to frame24, 15 to period15, 12 to period12)) {
            val start = 5_000_000_000L
            val a = FeatureAggregator(start / 1_000_000L, Synth.UTC0, gapThresholdNs = GapThresholds.gapThresholdNs(period), longGapThresholdNs = GapThresholds.longGapThresholdNs(period), sessionStartRawNs = start)
            a.onScene(SceneSample(start, 118.0, 4.0, 9.0))
            fun processed(raw: Long) = a.onFrameProcessed(ProcessedFrame(raw, 15.0, null))
            processed(start)
            processed(start + 2 * period) // two-frame interval: over the gap threshold
            processed(start + 2 * period + 4 * period + 500_000L) // four frames + 0.5 ms jitter: not a long gap
            processed(start + 2 * period + 4 * period + 500_000L + 5 * period) // five frames: long gap
            val closed = a.closeBuckets(start / 1_000_000L + 20_000, device)
            val gaps = closed.sumOf { it.second.gapsOverThreshold }
            val long = closed.sumOf { it.second.gapsOverLongThreshold }
            assertEquals(3, gaps, "$fps fps: 2, 4 and 5 frame intervals are all over 1.5 frames")
            assertEquals(1, long, "$fps fps: only the 5-frame interval is over 4.5 frames")
        }
        // a single missed slot at 15 Hz is a gap over the threshold
        val raws = stream(24.0, 2.0)
        val s2 = Session(raws[0], period15, frame24)
        var slotIndex = 0
        for (r in raws) {
            s2.captureResult(r)
            if (!s2.started) { s2.frame(r); slotIndex++; continue } // the first frame starts the session through the harness
            val out = s2.scheduler.onFrameReceived(s2.fr(r))
            if (out == FrameScheduler.FrameOutcome.SLOT) {
                slotIndex++
                if (slotIndex == 10) s2.scheduler.onFaceInferenceError(s2.fr(r)) else { s2.scheduler.onFaceSucceeded(s2.fr(r)); s2.agg.onFrameProcessed(ProcessedFrame(r, 15.0, null)) }
            } else if (out == FrameScheduler.FrameOutcome.NOT_SLOT) s2.scheduler.onFrameSkipped(s2.fr(r))
        }
        val closed = s2.closeAll(s2.startMonoMs + 5_000)
        assertEquals(1L, s2.agg.totals.processingSlotsMissed)
        assertEquals(1, closed.sumOf { it.second.gapsOverThreshold }, "the missed slot shows as one gap over 100 ms")
        assertEquals(0, closed.sumOf { it.second.gapsOverLongThreshold })
    }

    // ---- (o) a capture result after CLOSE: after_close = 1, stop_integrity_failed; session_end is the fence even when writing takes 700 ms

    @Test
    fun o_aCaptureResultAfterCloseIsAStopIntegrityFailureAndSessionEndStaysAtTheFence() {
        val raws = stream(24.0, 2.0)
        val s = Session(raws[0], period15, frame24)
        for (r in raws.dropLast(1)) s.both(r)
        val straggler = raws.last() // captured before the fence, its capture result is late
        val fenceRaw = straggler + frame24 / 2
        val fenceMs = fenceRaw / 1_000_000L
        var writeClock = 0L
        val r = StopSequence(
            stopInputs = { fenceMs },
            raiseFence = { f -> s.scheduler.fence(fenceRaw); s.agg.stopInputs(f, fenceRaw) },
            awaitAnalysisIdle = { 0L },
            closeSlotScheduler = { val n = s.scheduler.close(); assertEquals(FrameScheduler.CaptureDecision.AFTER_CLOSE, s.captureResult(straggler)); n },
            closePoseSlot = { },
            awaitPoseIdle = { 0L },
            drainAggregationQueue = { true },
            finish = { f -> StopFinalizer.finish(s.agg, f, s.startMonoMs, Synth.UTC0, device, SessionEndReason.USER) },
            writeEnd = { writeClock = fenceMs + 700 }, // the summary takes 700 ms; the end marker was stamped before
        ).run()
        assertEquals(1L, r.totals.captureResultsAfterClose)
        assertTrue(r.stopIntegrityFailed)
        assertEquals(listOf("${StopIntegrity.REASON_AFTER_CLOSE} 1건"), r.stopIntegrity.reasons)
        assertEquals(true, r.end.stopIntegrityFailed)
        assertEquals(1L, r.end.captureResultsAfterClose)
        assertEquals(true, r.end.captureResultDrainComplete)
        assertEquals(true, r.end.aggregationQueueDrained)
        assertEquals(emptyList(), r.mismatches, "the relations pass: the straggler is requested and a backpressure drop, just not expected")
        assertEquals(fenceMs, r.end.tMonoMs, "session_end = fence, not the write time $writeClock")
        assertEquals(Synth.UTC0 + (fenceMs - s.startMonoMs), r.end.tUtcMs)
        val log = SessionLog(fixedHeader("E15", FaceSchedule.SLOT, period15, s.startMonoMs), r.records.map { it.second }, sessionEnd = r.end, v0bRaw = r.records.map { it.raw })
        val summary = V0bReport.build(log, stop = StopSummary(checked = true, mismatches = r.mismatches, totals = r.totals, captureResultDrainComplete = r.captureResultDrainComplete, aggregationQueueDrained = r.queueDrained))
        assertEquals(true, summary.overall.diagnostics.stopIntegrityFailed)
        assertEquals(ComparisonState.NOT_COMPARABLE, summary.comparability.state)
        val text = summary.render()
        assertEquals(V0bReport.NOT_COMPARABLE_PREFIX + "${StopIntegrity.REASON_AFTER_CLOSE} 1건(stop_integrity_failed)", text.lines()[0], text)
        assertEquals(V0bReport.COUNTER_OK, text.lines()[1], text)
        assertTrue(text.lines()[2].startsWith(V0bReport.STOP_INTEGRITY_FAILED_PREFIX + StopIntegrity.REASON_AFTER_CLOSE), text)
        assertTrue("after_close 1" in text, text)
        // rebuilt from the JSONL alone (recovery / re-analysis) the flag and its cause still come from the session_end line
        val recovered = V0bReport.build(log)
        assertEquals(true, recovered.overall.diagnostics.stopIntegrityFailed)
        assertNotNull(recovered.overall.diagnostics.captureResultsAfterClose)
        assertEquals(listOf("${StopIntegrity.REASON_AFTER_CLOSE} 1건"), recovered.overall.diagnostics.integrityReasons)
        // a *post-fence* capture result after CLOSE was never a candidate for expected: after-fence, not an integrity failure
        val s2 = Session(raws[0], period15, frame24)
        for (r in raws) s2.both(r)
        val f2 = raws.last() + frame24 / 2
        s2.scheduler.fence(f2)
        s2.agg.stopInputs(f2 / 1_000_000L, f2)
        s2.scheduler.close()
        assertEquals(FrameScheduler.CaptureDecision.AFTER_FENCE, s2.captureResult(raws.last() + 2 * frame24))
        assertEquals(0L, s2.agg.totals.captureResultsAfterClose)
        assertEquals(1L, s2.agg.totals.captureResultsAfterFence)
        assertEquals(1L, s2.scheduler.captureResultsAfterCloseAfterFence)
        assertEquals(false, StopIntegrity.of(s2.agg.totals, captureResultDrainComplete = true, aggregationQueueDrained = true).failed)
    }

    // ---- (p) E2 2.1: a fence exactly on a bucket boundary — the end clamp must point at the last bucket that exists

    @Test
    fun p_aFenceExactlyOnABucketBoundaryClampsAPreFenceStragglerIntoTheLastEmittedBucket() {
        val raws = stream(24.0, 2.0) // 48 frames, the last at +1958.3 ms
        val s = Session(raws[0], null, frame24) // REALTIME: raw == mono
        for (r in raws) s.both(r)
        val fenceMonoMs = s.startMonoMs + 2_000 // fenceMono − sessionStartMono = 2000 ms exactly: buckets 0 and 1 are complete, bucket 2 begins at the fence
        val fenceRaw = fenceMonoMs * 1_000_000L
        s.scheduler.fence(fenceRaw)
        s.agg.stopInputs(fenceMonoMs, fenceRaw)
        val stragglerRaw = fenceRaw - 1_000_000L // 1 ms before the raw fence: inside the window by identity
        val staleMono = fenceMonoMs * 1_000_000L + 400_000_000L // converted with an older offset: 400 ms past the mono fence, bucket 2 by position
        val st = CameraStamp(stragglerRaw, staleMono)
        val before = s.agg.totals
        assertEquals(FrameScheduler.CaptureDecision.SELECTED, s.scheduler.onCaptureResult(st))
        assertEquals(FrameScheduler.FrameOutcome.SLOT, s.scheduler.onFrameReceived(st))
        assertTrue(s.scheduler.onFaceSucceeded(st))
        s.agg.onFrameProcessed(ProcessedFrame(staleMono, 15.0, FrameSample(staleMono, 1_000_000L, false, rawSensorTs = stragglerRaw), rawSensorTs = stragglerRaw))
        val t = s.agg.totals
        assertEquals(before.framesSampleApplied + 1, t.framesSampleApplied, "admitted by raw, applied")
        assertEquals(0L, t.framesSampleLateDropped)
        val out = StopFinalizer.finish(s.agg, fenceMonoMs, s.startMonoMs, Synth.UTC0, device, SessionEndReason.USER)
        assertEquals(2, out.records.size, "buckets 0 and 1 are complete at a fence of exactly +2000 ms")
        val last = out.records[1]
        assertEquals(s.startMonoMs + 1_000, last.second.tMonoMs)
        assertEquals(25, last.second.framesRequested, "24 stream frames of second 1 plus the straggler")
        assertEquals(25, last.second.framesProcessed)
        assertEquals(25, last.second.framesSampleApplied)
        assertEquals(t.framesSampleApplied, out.records.sumOf { it.second.framesSampleApplied.toLong() }, "an applied frame never vanishes from the records: (fence − start) ÷ period would have put it into bucket 2, which is never emitted")
        assertEquals(t.framesRequested, out.records.sumOf { it.second.framesRequested.toLong() })
        assertEquals(emptyList(), CounterConsistency.check(out.totals))
    }

    // ---- (q) E2 2.3: an out-of-order capture result is a diagnostic counter; in slot mode it makes the session not comparable

    @Test
    fun q_anOutOfOrderCaptureResultInSlotModeIsCountedInTheEndLineAndMakesTheSessionNotComparable() {
        val raws = stream(24.0, 2.0)
        fun run(periodNs: Long?): Pair<Session, StopResult> {
            val s = Session(raws[0], periodNs, frame24)
            for (r in raws.take(10)) s.both(r)
            s.frame(raws[11]) // frame 11 arrives before any capture result of frames 10 / 11
            assertEquals(FrameScheduler.CaptureDecision.OUT_OF_ORDER, s.captureResult(raws[10]), "the capture result of the frame before it trails")
            assertEquals(FrameScheduler.CaptureDecision.DUPLICATE, s.captureResult(raws[11]))
            for (r in raws.drop(12)) s.both(r)
            return s to s.stop(raws.last() + frame24 / 2)
        }
        val (slot, rs) = run(period15)
        assertEquals(1L, slot.scheduler.captureResultsOutOfOrder)
        assertEquals(1L, rs.totals.captureResultsOutOfOrder, "the scheduler hands each out-of-order capture result to the sink")
        assertEquals(1L, rs.end.captureResultsOutOfOrder, "recorded on the session_end line")
        assertEquals(emptyList(), rs.mismatches)
        assertFalse(rs.stopIntegrityFailed, "out of order is not a stop-integrity cause")
        val slotLog = SessionLog(fixedHeader("E15", FaceSchedule.SLOT, period15, slot.startMonoMs), rs.records.map { it.second }, sessionEnd = rs.end, v0bRaw = rs.records.map { it.raw })
        val slotSummary = V0bReport.build(slotLog, stop = StopSummary(checked = true, totals = rs.totals, captureResultDrainComplete = true, aggregationQueueDrained = true))
        assertEquals(1L, slotSummary.overall.diagnostics.captureResultsOutOfOrder)
        assertEquals(ComparisonState.NOT_COMPARABLE, slotSummary.comparability.state)
        assertEquals(listOf("${V0bReport.REASON_OUT_OF_ORDER} 1건"), slotSummary.comparability.reasons)
        val text = slotSummary.render()
        assertEquals(V0bReport.NOT_COMPARABLE_PREFIX + "${V0bReport.REASON_OUT_OF_ORDER} 1건", text.lines()[0], text)
        assertTrue(text.lines().any { it.startsWith(V0bReport.OUT_OF_ORDER_PREFIX + "1건") }, text)
        assertTrue("out_of_order 1" in text, text)
        assertEquals(1L, V0bReport.build(slotLog).overall.diagnostics.captureResultsOutOfOrder, "the recovered summary reads it from the end line")
        // every-frame mode: the same event is a processing opportunity (expected + missed by backpressure), shown as a count, and the session stays comparable
        val (every, re) = run(null)
        assertEquals(1L, every.scheduler.captureResultsOutOfOrder)
        assertEquals(1L, re.end.captureResultsOutOfOrder)
        assertEquals(1L, re.totals.processingSlotsMissed)
        val everyLog = SessionLog(fixedHeader("A", FaceSchedule.EVERY_FRAME, frame24, every.startMonoMs), re.records.map { it.second }, sessionEnd = re.end, v0bRaw = re.records.map { it.raw })
        val everySummary = V0bReport.build(everyLog, stop = StopSummary(checked = true, totals = re.totals, captureResultDrainComplete = true, aggregationQueueDrained = true))
        assertEquals(ComparisonState.COMPARABLE, everySummary.comparability.state, everySummary.comparability.toString())
        assertTrue("out_of_order 1" in everySummary.render())
    }

    // ---- (r) E2 1장: fps unset (neither [24,24] nor [30,30]) — no 30 fps assumption; the diagnostic interval is the warm-up's capture-interval median

    @Test
    fun r_anUnsetFpsSessionLearnsItsDiagnosticIntervalFromTheWarmupAndIsNeverJudged() {
        val fps = 27.5 // whatever the HAL default happens to be
        val all = stream(fps, 75.0)
        val interval = (1e9 / fps).roundToLong()
        fun gapAt(sec: Int) = all.indexOfFirst { it - all[0] >= sec * 1_000_000_000L }
        val g1 = gapAt(30) // a 3-frame gap inside the warm-up
        val g2 = gapAt(70) // and one after it
        val raws = all.filterIndexed { i, _ -> i != g1 && i != g1 + 1 && i != g2 && i != g2 + 1 }
        val s = Session(raws[0], null, GapThresholds.frameIntervalNs(30), learnFromWarmup = true)
        assertNull(s.agg.currentGapThresholdNs, "no expected interval is assumed at the start")
        for (r in raws.filter { it - raws[0] < 59_000_000_000L }) s.both(r)
        val early = s.closeAll(s.startMonoMs + 59_500)
        assertNull(s.agg.learnedExpectedIntervalNs, "nothing is known before the warm-up ends")
        assertEquals(59, early.size)
        val warmGap = early[30].second
        assertEquals(0, warmGap.gapsOverThreshold, "no threshold in force during the warm-up")
        assertEquals(1, warmGap.gapsOver80Ms, "the fixed 80 ms diagnostic still counts the 109 ms gap")
        assertEquals(109L, warmGap.maxFrameGapMs)
        // the aggregation tick closes bucket 59 at ~60.3 s, before the frames of the 70th second arrive
        for (r in raws.filter { it - raws[0] >= 59_000_000_000L && it - raws[0] < 61_000_000_000L }) s.both(r)
        val atSixtyOne = s.closeAll(s.startMonoMs + 61_400)
        assertEquals(listOf(59L, 60L), atSixtyOne.map { (it.second.tMonoMs - s.startMonoMs) / 1000 })
        val learned = assertNotNull(s.agg.learnedExpectedIntervalNs, "learned when the last warm-up bucket closed")
        for (r in raws.filter { it - raws[0] >= 61_000_000_000L }) s.both(r)
        val rest = atSixtyOne + s.closeAll(s.startMonoMs + 76_000)
        assertTrue(abs(learned - interval) <= 2L, "learned $learned ns vs the real interval $interval ns")
        assertEquals(GapThresholds.gapThresholdNs(learned), s.agg.currentGapThresholdNs)
        assertEquals(GapThresholds.longGapThresholdNs(learned), s.agg.currentLongGapThresholdNs)
        val records = early + rest
        val lateGap = records[70].second
        assertEquals(1, lateGap.gapsOverThreshold, "after the warm-up a 3-frame gap (109 ms) is over 1.5 × 36.4 ms")
        assertEquals(0, lateGap.gapsOverLongThreshold)
        // the summary: thresholds n/a, the learned diagnostic shown, nothing judged, "비교 불가: fps unset(가변)"
        val fenceRaw = raws.last() + interval
        val r = s.stop(fenceRaw)
        val header = Synth.header.copy(
            tStartMonoMs = s.startMonoMs, capturePreset = "A", nominalFps = 0, cameraFpsRangesSupported = "[15,30]", faceSchedule = FaceSchedule.EVERY_FRAME,
            faceProcessPeriodNs = null, frameGapThresholdNs = null, frameLongGapThresholdNs = null, frameGapThresholdMs = null, frameLongGapThresholdMs = null,
        )
        assertTrue(header.cameraFpsUnset)
        assertEquals(SessionHeader.FPS_UNSET_LABEL, header.cameraFpsRequestLabel)
        val log = SessionLog(header, (records + r.records).map { it.second }, sessionEnd = r.end, v0bRaw = (records + r.records).map { it.raw })
        val summary = V0bReport.build(log, stop = StopSummary(checked = true, totals = r.totals, captureResultDrainComplete = true, aggregationQueueDrained = true))
        val th = summary.overall.thresholds
        assertFalse(th.applicable)
        assertTrue(th.learnedFromWarmup)
        assertEquals(learned / 1e6, assertNotNull(th.expectedIntervalMs), 1e-6)
        assertEquals("n/a", th.gapLabel)
        assertEquals("n/a", th.longGapLabel)
        assertEquals("${Stats.fmt(learned / 1e6 * 1.5, 1)}ms", th.gapCountedLabel)
        assertFalse(summary.pass.judged)
        assertEquals(SessionHeader.FPS_UNSET_LABEL, summary.pass.notJudgedReason)
        assertNull(summary.overall.cadence.mismatch, "no request: no cadence verdict")
        assertEquals(ComparisonState.NOT_COMPARABLE, summary.comparability.state)
        assertEquals(listOf(V0bReport.REASON_FPS_UNSET), summary.comparability.reasons)
        val text = summary.render()
        assertEquals(V0bReport.NOT_COMPARABLE_PREFIX + V0bReport.REASON_FPS_UNSET, text.lines()[0], text)
        assertTrue(text.lines().any { it.startsWith(V0bReport.FPS_UNSET_PREFIX) && "진단용 기대 간격 = 워밍업 60초 CaptureResult 간격 중앙값 ${Stats.fmt(learned / 1e6, 1)}ms" in it }, text)
        assertTrue("@ ${SessionHeader.FPS_UNSET_LABEL}(CameraX 실제 선택)" in text, text)
        assertTrue("카메라 ${SessionHeader.FPS_UNSET_LABEL}, 갭 임계 n/a" in text, text)
        assertTrue("합격 판정 안 함(프리셋 A, ${SessionHeader.FPS_UNSET_LABEL})" in text, text)
        assertEquals(summary, V0bReport.build(co.byite.focus.core.log.JsonlCodec.decode(co.byite.focus.core.log.JsonlCodec.encode(log)), stop = summary.stop), "null ms thresholds round-trip")
        // a session that ends inside the warm-up learns nothing and says so
        val short = V0bReport.build(SessionLog(header, records.take(40).map { it.second }, sessionEnd = SessionEnd(s.startMonoMs + 40_000, Synth.UTC0 + 40_000, SessionEndReason.USER), v0bRaw = records.take(40).map { it.raw }), stop = checkedStop)
        assertNull(short.overall.thresholds.expectedIntervalMs)
        assertEquals("-", short.overall.thresholds.gapCountedLabel)
        assertTrue("워밍업 60초 미완료" in short.render(), short.render())
        // a slot preset on an unset camera keeps the slot period as its (diagnostic) expected interval and is still not judged
        val e15 = V0bReport.thresholdLine(header.copy(capturePreset = "E15", faceSchedule = FaceSchedule.SLOT, faceProcessPeriodNs = period15, frameGapThresholdNs = GapThresholds.gapThresholdNs(period15), frameLongGapThresholdNs = GapThresholds.longGapThresholdNs(period15), frameGapThresholdMs = 100, frameLongGapThresholdMs = 300))
        assertFalse(e15.applicable)
        assertFalse(e15.learnedFromWarmup)
        assertEquals(100.0, assertNotNull(e15.gapMs), 1e-6)
    }

    // ---- review: an in-window capture result that trails a later frame (every-frame mode) is still a slot — and a lost one

    @Test
    fun anOutOfOrderCaptureResultInEveryFrameModeIsAnExpectedSlotThatIsMissedWhenItsFrameCanNoLongerCome() {
        val start = 5_000_000_000L
        val s = Session(start, null, frame24)
        s.both(start)
        // frame 1 was dropped by KEEP_ONLY_LATEST and its capture result trails frame 2
        s.frame(start + 2 * frame24)
        assertEquals(FrameScheduler.CaptureDecision.OUT_OF_ORDER, s.captureResult(start + frame24))
        assertEquals(FrameScheduler.CaptureDecision.DUPLICATE, s.captureResult(start + 2 * frame24))
        val t = s.agg.totals
        assertEquals(3L, t.framesRequested)
        assertEquals(2L, t.framesAnalyzerReceived)
        assertEquals(3L, t.processingSlotsExpected, "every capture result in the window is an opportunity, whatever its arrival order")
        assertEquals(2L, t.processingSlotsFilled)
        assertEquals(1L, t.processingSlotsMissed, "its frame was lost to backpressure")
        assertEquals(1L, s.scheduler.slotsFromOutOfOrder)
        assertEquals(1L, s.scheduler.slotsMissedByBackpressure)
        assertEquals(emptyList(), CounterConsistency.check(t))
        // trailing only a later *capture result* (its own frame may still come): the slot stays open and the frame fills it
        val s2 = Session(start, null, frame24)
        s2.both(start)
        assertEquals(FrameScheduler.CaptureDecision.SELECTED, s2.captureResult(start + 2 * frame24))
        assertEquals(FrameScheduler.CaptureDecision.OUT_OF_ORDER, s2.captureResult(start + frame24))
        assertEquals(2, s2.scheduler.openSlots)
        assertEquals(FrameScheduler.FrameOutcome.SLOT, s2.frame(start + frame24))
        assertEquals(FrameScheduler.FrameOutcome.SLOT, s2.frame(start + 2 * frame24))
        assertEquals(3L, s2.agg.totals.processingSlotsFilled)
        assertEquals(0L, s2.agg.totals.processingSlotsMissed)
        // slot mode: the rule has already advanced; an out-of-order result is not selected and a lost frame shows as a gap
        val s3 = Session(start, period15, frame24)
        s3.both(start)
        s3.frame(start + 2 * frame24)
        assertEquals(FrameScheduler.CaptureDecision.OUT_OF_ORDER, s3.captureResult(start + frame24))
        assertEquals(0L, s3.scheduler.slotsFromOutOfOrder)
        assertEquals(emptyList(), CounterConsistency.check(s3.agg.totals))
    }

    // ---- review: gap causes compare the cycle with the expected processing interval, not with threshold ÷ 2

    @Test
    fun gapCauseUsesTheExpectedProcessingIntervalAsTheCycleCriterion() {
        val start = 5_000_000_000L
        val a = FeatureAggregator(
            start / 1_000_000L, Synth.UTC0,
            gapThresholdNs = GapThresholds.gapThresholdNs(frame24), longGapThresholdNs = GapThresholds.longGapThresholdNs(frame24),
            sessionStartRawNs = start, expectedIntervalNs = frame24,
        )
        a.onScene(SceneSample(start, 118.0, 4.0, 9.0))
        // a 35 ms cycle is shorter than one frame interval (41.7 ms): the analyzer was not the bottleneck → "other"
        a.onFrameProcessed(ProcessedFrame(start, 30.0, FrameSample(start, 1_000_000L, false, wrapMs = 1.0, facePostMs = 0.5, totalMs = 35.0)))
        a.onFrameProcessed(ProcessedFrame(start + 2 * frame24, 15.0, FrameSample(start + 2 * frame24, 1_000_000L, false, totalMs = 20.0)))
        // a 45 ms cycle dominated by Face → Face
        a.onFrameProcessed(ProcessedFrame(start + 3 * frame24, 40.0, FrameSample(start + 3 * frame24, 1_000_000L, false, wrapMs = 1.0, facePostMs = 0.5, totalMs = 45.0)))
        a.onFrameProcessed(ProcessedFrame(start + 5 * frame24, 15.0, FrameSample(start + 5 * frame24, 1_000_000L, false, totalMs = 20.0)))
        val raw = a.closeBuckets(start / 1_000_000L + 1_300, device)[0].raw
        assertEquals(2, raw.gapCauses.values.sum())
        assertEquals(1, raw.gapCauseOther)
        assertEquals(1, raw.gapCauseFace)
    }
}
